# Generated by Django 5.1.6 on 2025-03-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('small_drop_threshold', models.FloatField(default=0)),
                ('large_drop_threshold', models.FloatField(default=0)),
                ('last_alert_sent', models.DateTimeField(blank=True, null=True)),
                ('alert_sent_today', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=10, unique=True)),
                ('stock_name', models.CharField(max_length=100)),
                ('market_type', models.IntegerField(choices=[(1, 'Listed'), (2, 'OTC')])),
                ('security_type', models.IntegerField(choices=[(1, 'Stock'), (2, 'ETF')])),
                ('industry', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('open', models.DecimalField(decimal_places=2, max_digits=10)),
                ('high', models.DecimalField(decimal_places=2, max_digits=10)),
                ('low', models.DecimalField(decimal_places=2, max_digits=10)),
                ('close', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.BigIntegerField()),
                ('price_change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_splits', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
            ],
            options={
                'unique_together': {('symbol', 'date')},
            },
        ),
    ]
