# Generated by Django 5.1.6 on 2025-03-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='threshold',
        ),
        migrations.AddField(
            model_name='stock',
            name='alert_sent_today',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stock',
            name='large_drop_threshold',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='last_alert_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='small_drop_threshold',
            field=models.FloatField(default=0),
        ),
    ]
